allowBuilds:
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  electron: true
  electron-winstaller: true
  tree-sitter: true
  tree-sitter-json: true

overrides:
  tmp: '~0.2.6'
  qs: '~6.15.2'
